name: currency_input_field
description: A reusable Flutter widget for selecting a currency and entering a monetary amount, with validation, flexible layouts, and configurable sizing.
version: 0.1.0
homepage: https://munyaradzichigangawa.co.zw
repository: https://github.com/Munyaradzi-Chigangawa/currency_input_field
issue_tracker: https://github.com/Munyaradzi-Chigangawa/currency_input_field/issues
license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter