name: currency_input_field
description: "A Flutter package for a currency and amount input field. It allows the user to input an amount and select a currency in a drop down."
version: 0.0.3
homepage: https://github.com/Munyaradzi-Chigangawa/currency_input_field
repository: https://github.com/Munyaradzi-Chigangawa/currency_input_field

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  intl: ^0.19.0
  provider: ^6.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
